# Generated by Django 5.1.6 on 2025-03-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_created_at'),
        ('products', '0002_remove_productsize_actual_price_and_more'),
    ]

    operations = [
    ]
